### ISSUE TITLE
Match iOS 7/8 style with little padding between labels

### ISSUE THREAD

**Issue by hipwelljo** [kreeger/BDKCollectionIndexView#13]
The table view index UI changed in iOS 7 to remove the large padding between labels, allowing the user to swipe a small amount of pixels compared to sliding their finger along the entire display or tapping. The collection index view should behave the same way. :)

**Comment by hipwelljo** [comment]
I have code for this, but it gets rid of the ability to specify endPadding. Not sure if this should be an option controlled by another public property or if it should just be the new behavior to match the latest OS design standards.

**Comment by kreeger** [comment]
@hipwelljo I'd say let's have this match the latest iOS design standards, and get rid of endPadding. I'll make sure this next release gets a major version bump!

**Comment by hipwelljo** [comment]
@kreeger Added pull request. When do you think the next release

**Comment by hipwelljo** [comment]
Cool! When do you think the next release will be, got some other cool updates? :)

**Comment by kreeger** [comment]
Merged and released as v2.0.0!
