### ISSUE TITLE
Missing initWithCoder: for Storyboard Layout

### ISSUE THREAD

**Issue by semireg** [kreeger/BDKCollectionIndexView#28]
It would be nice if initWithCoder: was available then it could be included in storyboards. This is related to one of the last comments in issue #2.

Quick gist: https://gist.github.com/semireg/f8168fe7b336723fd406

Also, note the tintColor needs to be set back to nil in viewDidLoad to remain the default blue.

**Comment by kreeger** [comment]
@semireg if you wouldn't mind implementing this in a feature branch and then opening a pull request, that would be awesome.

**Comment by kreeger** [comment]
Fixed with #29.
